### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by logixdev** [XCrafters/xcrBungeeAuth#10]
Cześć. Problem jest tego typu, że pomimo podpięcia do serwera Redisa, wpisania poprawnego portu, plugin wyrzuca błąd. Po zainstalowaniu Redisa na dedyku trzeba coś jeszcze z nim robić, żeby śmigało? Załączam log.
`18:00:16 [WARNING] Exception encountered when loading plugin: xcrBungeeAuth
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84)
	at pl.xcrafters.xcrbungeeauth.redis.RedisManager.<init>(RedisManager.java:24)
	at pl.xcrafters.xcrbungeeauth.AuthPlugin.onEnable(AuthPlugin.java:67)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:274)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Invalid argument (connect failed)
	at redis.clients.jedis.Connection.connect(Connection.java:150)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:71)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1783)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:65)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:40)
	... 7 more
Caused by: java.net.ConnectException: Invalid argument (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:144)
	... 14 more`

**Comment by defabricated** [comment]
Przecież pisze Ci, że nie może się z Redis'em połączyć. Coś masz źle albo w configu albo z redis'em.

**Comment by logixdev** [comment]
@defabricated wiem, widzę co jest napisane, tylko nie wiem jak to poprawić. Jaki powinien być format w configu?
Próbowałem tak: 
`redis://localhost:6379`
I tak:
`localhost:6379`

I nic. Sam Redis na pewno śmiga, po wpisaniu polecenia redis-cli wrzuca mnie w serwer.

**Comment by defabricated** [comment]
`redis:
      host: "127.0.0.1"
      port: "6379"`

**Comment by logixdev** [comment]
@defabricated To zmienia postać rzeczy, śmiga! Dzięki Tomek i czekamy na resztę pluginów. :)
