### ISSUE TITLE
Błąd podczas automatycznego tworzenia tabel MySQL!

### ISSUE THREAD

**Issue by HastyTM** [XCrafters/xcrBungeeAuth#8]
Log z konsoli podczas uruchamiania: 

17:48:42 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
17:48:42 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
17:48:42 [INFO] Enabled Travertine version git:Travertine-Bootstrap:1.12-SNAPSHOT:960f8cf:unknown
17:48:43 [INFO] Couldn't detect bungee version. Custom build?
17:48:43 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:43 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:43 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:43 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:43 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:43 [INFO] Loaded plugin xcrBungeeAuth version 1.1 by defabricated
17:48:43 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:44 [WARNING] Forced host server pvp is not defined
17:48:44 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:44 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:44 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:44 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:44 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:48 [SEVERE] maj 18, 2017 5:48:48 PM pl.xcrafters.xcrbungeeauth.AuthPlugin onEnable
SEVERE: null
java.sql.SQLException: Can not issue data manipulation statements with executeQuery().
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.StatementImpl.checkForDml(StatementImpl.java:463)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1926)
	at pl.xcrafters.xcrbungeeauth.mysql.MySQLManager.prepareUsersTable(MySQLManager.java:104)
	at pl.xcrafters.xcrbungeeauth.mysql.MySQLManager.<init>(MySQLManager.java:28)
	at pl.xcrafters.xcrbungeeauth.AuthPlugin.onEnable(AuthPlugin.java:63)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

17:48:49 [INFO] Enabled plugin xcrBungeeAuth version 1.1 by defabricated
17:48:49 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
17:48:50 [INFO] Listening on /0.0.0.0:25577
17:48:50 [INFO] Started query on /0.0.0.0:25577

**Comment by defabricated** [comment]
@MichalPrusak To chyba Twój kod.

**Comment by MichalPrusak** [comment]
Owszem, mój. Dlatego też niedługo wrzucę łatkę na to.

**Comment by MichalPrusak** [comment]
Łatka wrzucona, @defabricated merge pls
Zrób też release jeśli możesz, żeby błędu nie było.
